### PR TITLE
[-] Updated url call to use POST instead of GET

### PR DESCRIPTION
**Pull request by mickaelandrieu**
Hi,
The old GET url access is not available for some countries, but the POST call is.

I have also removed some checks on socket timeouts because `Tools:file_get_contents` already have a correct timeout. 

Mickaël

### CODE REVIEW

**Comment by vincentbz** [comment]
http://forge.prestashop.com/browse/NM-207

**Comment by mickaelandrieu** [comment]
ping @vincentbz can you confirm this contribution is OK / QA ?

**Comment by fire2** [comment]
It is not ok, please check my last comments on the forge report.

**Comment by Progi1984** [comment]
@mickaelandrieu This PR is always up to date ? Thank you for your answer.

**Comment by mickaelandrieu** [comment]
I don't know: I mean, it was do 5 years ago 😁.

Not merging my prs is an old habit 🙃.

Closed !

**Pull request closed without merging**
